package com.example.basiclayoutscodelab.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4F6603)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0EE82)
val md_theme_light_onPrimaryContainer = Color(0xFF161F00)
val md_theme_light_secondary = Color(0xFF9E4300)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onSecondaryContainer = Color(0xFF341100)
val md_theme_light_tertiary = Color(0xFF006971)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF84F3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF002023)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF330045)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF330045)
val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFFFEBFF)
val md_theme_light_inverseSurface = Color(0xFF4D1661)
val md_theme_light_inversePrimary = Color(0xFFB5D269)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4F6603)
val md_theme_light_outlineVariant = Color(0xFFC6C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB5D269)
val md_theme_dark_onPrimary = Color(0xFF273500)
val md_theme_dark_primaryContainer = Color(0xFF3A4D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0EE82)
val md_theme_dark_secondary = Color(0xFFFFB691)
val md_theme_dark_onSecondary = Color(0xFF552000)
val md_theme_dark_secondaryContainer = Color(0xFF793100)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_tertiary = Color(0xFF25DAEA)
val md_theme_dark_onTertiary = Color(0xFF00363B)
val md_theme_dark_tertiaryContainer = Color(0xFF004F55)
val md_theme_dark_onTertiaryContainer = Color(0xFF84F3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF330045)
val md_theme_dark_onBackground = Color(0xFFFAD7FF)
val md_theme_dark_surface = Color(0xFF330045)
val md_theme_dark_onSurface = Color(0xFFFAD7FF)
val md_theme_dark_surfaceVariant = Color(0xFF45483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B8)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF330045)
val md_theme_dark_inverseSurface = Color(0xFFFAD7FF)
val md_theme_dark_inversePrimary = Color(0xFF4F6603)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB5D269)
val md_theme_dark_outlineVariant = Color(0xFF45483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFCCD5AE)
